---
driver_config:
  digitalocean_client_id: <%= ENV['DIGITAL_OCEAN_CLIENT_ID'] %>
  digitalocean_api_key: <%= ENV['DIGITAL_OCEAN_API_KEY'] %>
  google_client_email: <%= ENV['GOOGLE_CLIENT_EMAIL'] %>
  google_key_location: <%= ENV['GOOGLE_KEY_LOCATION'] %>
  google_project: <%= ENV['GOOGLE_PROJECT'] %>

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: debian-7.0
  driver_plugin: gce
  driver_config:
    image_name: debian-7-wheezy-v20131120
    zone: <%= ENV['GCE_ZONE'] %>
    area: <%= ENV['GCE_AREA'] %>
    network: <%= ENV['GCE_NETWORK'] %>
    username: <%= ENV['GCE_USERNAME'] %>
    public_key_path: <%= ENV['GCE_PUBLIC_KEY_PATH'] %>
    ssh_key: <%= ENV['GCE_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-10.04
  driver_plugin: digitalocean
  driver_config:
    image_id: 14097
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-12.04
  driver_plugin: digitalocean
  driver_config:
    image_id: 1505447
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

- name: ubuntu-13.10
  driver_plugin: digitalocean
  driver_config:
    image_id: 1505699
    flavor_id: 63
    region_id: 4
    ssh_key_ids: <%= ENV['DIGITAL_OCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITAL_OCEAN_SSH_KEY_PATH'] %>
  run_list:
  - recipe[apt]

suites:
- name: default
  run_list:
  - recipe[fake::default]
  attributes: {}
