AlignParameters:
  Enabled: false

Encoding:
  Enabled: false

LineLength:
  Max: 200

HashSyntax:
  EnforcedStyle: hash_rockets

CyclomaticComplexity:
  Max: 11

# Configuration parameters: CountComments.
MethodLength:
  Max: 30
